server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jishi?useSSL=false
    username: root
    password: Hym2050865
  mail:
    host: smtp.qq.com #???????
    username: 417695971@qq.com #QQ??
    password: drvvnzlqxbddcahd #??????
    protocol: smtp #??????
    default-encoding: utf-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
